[package]
authors = ["ixsetf"]
edition = "2018"
name = "rustmania"
version = "0.1.0"

[dependencies]
clap = "2.33.0"
cpal = "0.10.0"
hound = "3.4.0"
lewton = "0.9.1"
minimp3 = "0.3.3"
nom = "5.0.1"
serde = "1.0.101"
serde_derive = "1.0.101"
toml = "0.5.4"
rayon = "1.2.0"
rand = "0.7.2"
bincode = "1.2.0"
serde_yaml = "0.8.11"
log = "0.4"
fern = "0.5"
array-init = "0.1.0"
graphics = { path = "graphics" }

[dependencies.ggez]
git = "https://github.com/ggez/ggez.git"

[dependencies.num-rational]
version = "0.2"
default-features = false
features = ["std", "bigint-std", "serde"]

[workspace]
members = ["graphics"]
